module.exports = {
  react: 'React',
  'react-dom': 'ReactDOM',
  redux: 'Redux',
  'react-redux': 'ReactRedux',
  'react-router': 'ReactRouter',
  'react-router-dom': 'ReactRouterDOM',
  moment: 'moment',
  xlsx: 'XLSX',
  axios: 'axios',
  i18next: 'i18next',
  'react-i18next': 'reactI18next',
  'i18next-browser-languagedetector': 'LanguageDetector',
  'antd/lib/locale/en_US': 'enUS',
  'antd/lib/locale/zh_CN': 'zhCN',
  // '@sentry/browser': 'Sentry',
}
